name: Release

on:
  release:
    types: [published]

jobs:
  gem:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          rubygems: latest

      - uses: rubygems/release-gem@v1.4.0
